POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Joel",
    "email": "joel@email.com",
    "password": "ilovesarah",
    "role":"ADMIN"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "ellie@email.com",
    "password": "souimune"
}

###

GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZiYjA5ODk4LTlmMjEtNGQ2NC04ZGUxLWQxOTJiOWYwNzM0ZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3Nzc5MDI0OSwiZXhwIjoxNjc3ODA4MjQ5fQ.x9RY0g3ycnItWLvfBFXbvwfsDuQ8DB7s2OD41PLOJtE
###

POST http://localhost:3003/recipe/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZiYjA5ODk4LTlmMjEtNGQ2NC04ZGUxLWQxOTJiOWYwNzM0ZCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3Nzc5MDI0OSwiZXhwIjoxNjc3ODA4MjQ5fQ.x9RY0g3ycnItWLvfBFXbvwfsDuQ8DB7s2OD41PLOJtE
Content-Type: application/json

{
    "title": "Yakissoba",
    "description": "Ingredientes: 200g de peito de frango, 200g de carne bovina, cenoura, brócolis, pimentão verde, vermelhoe e amarelo, maizena, shoyo e macarrão instantaneo"
}

###

GET http://localhost:3003/recipe/3f612dbf-5c20-497b-9a1f-1c6b72c74542
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM3YzM1NTUwLTk1NGItNDRmNS1iZjI2LTRjNDM3ZWFkNWNkOCIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2Nzc3OTAxMTYsImV4cCI6MTY3NzgwODExNn0.82XrWjl59wmlpIfJr2mwUqprPiKKFDqHFiS26z9ec0c

###

POST http://localhost:3003/user/follow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM3YzM1NTUwLTk1NGItNDRmNS1iZjI2LTRjNDM3ZWFkNWNkOCIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2Nzc3OTAxMTYsImV4cCI6MTY3NzgwODExNn0.82XrWjl59wmlpIfJr2mwUqprPiKKFDqHFiS26z9ec0c
Content-Type: application/json

{
    "id_followed":"fbb09898-9f21-4d64-8de1-d192b9f0734d"
}

###
POST http://localhost:3003/user/unfollow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzYzE0ZGZiLWUwZjAtNDczOC04YjMxLTA1YjQxMTc1NTUyOSIsImlhdCI6MTY3Nzc3OTU0NywiZXhwIjoxNjc3Nzk3NTQ3fQ.IC7fyZmkTC1CUKuoFYsBySP_7IlWAAk0Z5FagUzvMUI
Content-Type: application/json

{
    "id_followed":"e7ccf381-2be9-4f5c-9dd9-cfc90fe7d332"
}

###

GET http://localhost:3003/user/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM3YzM1NTUwLTk1NGItNDRmNS1iZjI2LTRjNDM3ZWFkNWNkOCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2Nzc3OTA0MDksImV4cCI6MTY3NzgwODQwOX0.XUVFpA9lUehU3sxARUFXw7UYrlhsZaL7qFdAmFZ_o8M

###
PUT http://localhost:3003/recipe/edit/3f612dbf-5c20-497b-9a1f-1c6b72c74542
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM3YzM1NTUwLTk1NGItNDRmNS1iZjI2LTRjNDM3ZWFkNWNkOCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2Nzc3OTA0MDksImV4cCI6MTY3NzgwODQwOX0.XUVFpA9lUehU3sxARUFXw7UYrlhsZaL7qFdAmFZ_o8M
Content-Type: application/json


{
    "title": "Panqueca da Ellie",
    "description": "Ingredientes: 200g de peito de frango, Sal, pimenta do reino, orégano, 2 ovos, trigo, leite e fermento. Misture no liquidificador os ovos, trigo, leite, sal, pimenta do reino e orégano. Após tudo uniforme, insira o fermento e bata novamente. Cozinhe o frango ao seu gosto e desfie ele."
}
